{
  "hash": "f67b3b848bdc5e1d92e616c65a544033",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"CHANGE TITLE AFTER ANALYSIS!\"\nauthor: \"Landon Power\"\ndate: last-modified\nformat: \n  html:\n    editor: visual\n    toc: true\n    toc_float: true\n    number-sections: true\n    embed-resources: true\n    date-format: iso\n    theme: paper\n---\n\n\n\n# Setup and Data Ingest\n\n## Setup\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(janitor)\nlibrary(knitr)\nlibrary(magrittr)\nlibrary(broom)\nlibrary(naniar)\nlibrary(patchwork)\nlibrary(modelsummary)\nlibrary(pwr)\nlibrary(haven) # Package to ingest SAS transport files for 2017-2020 Pre-pandemic NHANES data\nlibrary(Hmisc)\nlibrary(tidyverse)\n\nsource(\"data/Love-boost.R\")\n\ntheme_set(theme_light())  # or use theme_set(theme_bw())\nknitr::opts_chunk$set(comment=NA)\n```\n:::\n\n\n\n## Data Ingest\n\nI ingested the demographic raw data from the NHANES 2017-2020 Pre-Pandemic Demographic data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Initially save the data from the NHANES Pre-pandemic 2017-2020 SAS transport\n#demographic <- haven::read_xpt(\"data/P_DEMO.xpt\")\n\n#saveRDS(demographic, \"data/P_DEMO.Rds\")\n\n# Simply read the tibble after data are saved\ndemographic <- readRDS(\"data/P_DEMO.Rds\")\n```\n:::\n\n\n\nI ingested the standard biochemistry panel raw data from the NHANES 2017-2020 Pre-Pandemic Laboratory data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Initially save the data from the NHANES Pre-pandemic 2017-2020 SAS transport\n#biochem <- haven::read_xpt(\"data/P_BIOPRO.xpt\")\n\n#saveRDS(biochem, \"data/P_BIOPRO.Rds\")\n\n# Simply read the tibble after data are saved\nbiochem <- readRDS(\"data/P_BIOPRO.Rds\")\n```\n:::\n\n\n\nFinally, I ingested the Alcohol Use raw data from the NHANES 2017-2020 Pre-Pandemic Questionnaire data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Initially save the data from the NHANES Pre-pandemic 2017-2020 SAS transport\n#alcohol <- haven::read_xpt(\"data/P_ALQ.xpt\")\n\n#saveRDS(alcohol, \"data/P_ALQ.Rds\")\n\n# Simply read the tibble after data are saved\nalcohol <- readRDS(\"data/P_ALQ.Rds\")\n```\n:::\n\n\n\n# Cleaning the Data\n\nI then merged the NHANES files before cleaning and selecting my variables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfull_uncleaned1 <- left_join(demographic, biochem, by = \"SEQN\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfull_uncleaned2 <- left_join(full_uncleaned1, alcohol, by = \"SEQN\")\n```\n:::\n\n\n\nThen I cleaned the variables and selected only the variables I will use in analysis. I first cleaned the names of all the variables in the `full_uncleaned2` dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfull <- full_uncleaned2 %>%\n  clean_names() %>%\n  mutate(across(where(is_character), as_factor))\n```\n:::\n\n\n\nI then selected the variables I will analyze and refined the observations to include only subjects who:\n\n-   had a `ridstatr` value of 2, meaning they were both interviewed and examined (N = 14,300)\n\n-   had a `ridageyr` between 21 and 79 years old (N = 7,853)\n\nFor my analysis, I then filtered to the proper variables I will analyze:\n\n-   Analysis A: two quantitative variables\n\n    -   alanine aminotransferase (ALT, in U/L)\n\n    -   aspartate aminotransferase (AST, in U/L)\n\n-   Analysis B: outcome (ALT) and binary categorical variable (gender)\n\n-   Analysis C: outcome (ALT) and multi-categorical variable (Race/Hispanic origin)\n\n-   Analysis E: J x K table of two categorical variables\n\n    -   J (2-5 levels): Ever had 4/5 or more drinks every day? (2 levels, Yes/No)\n\n    -   K (3-5 levels): Race/Hispanic origin (5 levels)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliver_damage <- full %>%\n  filter(ridstatr == \"2\") %>%\n  filter(between(ridageyr, 21, 79)) %>%\n  select(seqn, ridstatr, ridageyr, lbxsatsi, lbxsassi, \n         riagendr, ridreth1, alq151) %>%\n  mutate(riagendr = fct_recode(factor(riagendr), \n                            \"male\" = \"1\", \n                            \"female\" = \"2\")) %>%\n  mutate(ridreth1 = fct_recode(factor(ridreth1), \n                            \"Mexican American\" = \"1\", \n                            \"Other Hispanic\" = \"2\",\n                            \"Non-Hispanic White\" = \"3\",\n                            \"Non-Hispanic Black\" = \"4\",\n                            \"Other/Multi-Racial\" = \"5\")) %>%\n  mutate(alq151 = fct_recode(factor(alq151), \n                            \"yes\" = \"1\", \n                            \"no\" = \"2\",\n                            \"Refused\" = \"7\",\n                            \"Don't Know\" = \"9\"))\n\nhead(liver_damage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n    seqn ridstatr ridageyr lbxsatsi lbxsassi riagendr ridreth1           alq151\n   <dbl>    <dbl>    <dbl>    <dbl>    <dbl> <fct>    <fct>              <fct> \n1 109266        2       29       15       14 female   Other/Multi-Racial no    \n2 109271        2       49        8       14 male     Non-Hispanic White yes   \n3 109273        2       36       35       27 male     Non-Hispanic White no    \n4 109274        2       68       19       20 male     Other/Multi-Racial no    \n5 109282        2       76       17       19 male     Non-Hispanic White no    \n6 109284        2       44       16       15 female   Mexican American   <NA>  \n```\n\n\n:::\n:::\n\n\n\n# Codebook and Data Description\n\n7853 adults ages 21-79 participating in the NHANES 2017-2020 with data on the variables listed below. The data will be filtered to the complete cases in each discrete analysis as it is completed.\n\n## Codebook\n\n| Variable | Type | Description |\n|:--:|:--:|:--:|\n| **SEQN** | ID | Respondent sequence number |\n| **lbxsatsi** | Quant | Alanine aminotransferase (ALT; in U/L) |\n| **lbxsassi** | Quant | Aspartate aminotransferase (AST; in U/L) |\n| **riagendr** | Binary | Gender |\n| **ridreth1** | 5-Cat | Race/Hispanic origin (1 = Mexican American, 2 = Other Hispanic, 3 = Non-Hispanic White, 4 = Non-Hispanic Black, 5 = Other Race, Including Multi-Racial) |\n| **alq151** | Binary | Period of life where subject ever had more than 4/5 drinks every day? (1 = Yes, 2 = No, 7 = Refused, 9 = Don't know) |\n\n## Analytic Tibble\n\nThe complete tibble and a summary of the variables that are missing values is shown below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliver_damage\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7,853 × 8\n     seqn ridstatr ridageyr lbxsatsi lbxsassi riagendr ridreth1           alq151\n    <dbl>    <dbl>    <dbl>    <dbl>    <dbl> <fct>    <fct>              <fct> \n 1 109266        2       29       15       14 female   Other/Multi-Racial no    \n 2 109271        2       49        8       14 male     Non-Hispanic White yes   \n 3 109273        2       36       35       27 male     Non-Hispanic White no    \n 4 109274        2       68       19       20 male     Other/Multi-Racial no    \n 5 109282        2       76       17       19 male     Non-Hispanic White no    \n 6 109284        2       44       16       15 female   Mexican American   <NA>  \n 7 109286        2       33       10       13 female   Other/Multi-Racial <NA>  \n 8 109290        2       68       19       18 female   Non-Hispanic Black no    \n 9 109291        2       42       11       25 female   Other/Multi-Racial <NA>  \n10 109292        2       58       21       18 male     Other Hispanic     no    \n# ℹ 7,843 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngg_miss_var(liver_damage)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmiss_var_summary(liver_damage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  variable n_miss pct_miss\n  <chr>     <int>    <num>\n1 alq151     1149    14.6 \n2 lbxsassi    637     8.11\n3 lbxsatsi    606     7.72\n4 seqn          0     0   \n5 ridstatr      0     0   \n6 ridageyr      0     0   \n7 riagendr      0     0   \n8 ridreth1      0     0   \n```\n\n\n:::\n:::\n\n\n\n## Data Summary\n\n### Alanine aminotransferase (ALT; in U/L)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(liver_damage$lbxsatsi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nliver_damage$lbxsatsi : Alanine Aminotransferase (ALT) (U/L) \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n    7247      606      146    0.999    22.59     14.8        9       10 \n     .25      .50      .75      .90      .95 \n      13       18       26       39       51 \n\nlowest :   2   3   4   5   6, highest: 208 211 213 338 682\n```\n\n\n:::\n:::\n\n\n\n### Aspartate aminotransferase (AST; in U/L)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(liver_damage$lbxsassi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nliver_damage$lbxsassi : Aspartate Aminotransferase (AST) (U/L) \n       n  missing distinct     Info     Mean      Gmd      .05      .10 \n    7216      637      122    0.997    21.95    10.02    12.00    13.00 \n     .25      .50      .75      .90      .95 \n   16.00    19.00    24.00    31.00    38.25 \n\nlowest :   6   7   8   9  10, highest: 218 272 294 307 489\n```\n\n\n:::\n:::\n\n\n\n### Gender\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(liver_damage$riagendr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nliver_damage$riagendr \n       n  missing distinct \n    7853        0        2 \n                        \nValue        male female\nFrequency    3794   4059\nProportion  0.483  0.517\n```\n\n\n:::\n:::\n\n\n\n### Race/Hispanic origin\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(liver_damage$ridreth1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nliver_damage$ridreth1 \n       n  missing distinct \n    7853        0        5 \n                                                                   \nValue        Mexican American     Other Hispanic Non-Hispanic White\nFrequency                 945                847               2491\nProportion              0.120              0.108              0.317\n                                                \nValue      Non-Hispanic Black Other/Multi-Racial\nFrequency                2179               1391\nProportion              0.277              0.177\n```\n\n\n:::\n:::\n\n\n\n### Period of life where subject ever had more than 4/5 drinks every day?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(liver_damage$alq151)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nliver_damage$alq151 \n       n  missing distinct \n    6704     1149        4 \n                                                      \nValue             yes         no    Refused Don't Know\nFrequency        1061       5633          1          9\nProportion      0.158      0.840      0.000      0.001\n```\n\n\n:::\n:::\n\n\n\n# Analysis A: Comparing 2 Means with Paired Samples\n\n## The Question\n\nTo find a good proxy for liver damage, I decided to compares the means of two quantitative variables from the NHANES 2017-2020 dataset. There were 7247 NHANES participants with complete ALT values and 7216 NHANES participants with complete AST values.\n\n**Question:** Since both elevated ALT and AST are indicators of liver damage and since these variables are collected on each of the participants and can be considered paired samples, do the means of these two enzymmatic markers of liver function closely approximate each other, such that they are not significantly different?\n\n**Expectation:** Both ALT and AST are functionally related enzymmatic markers, even though elevated ALT is more characteristic of liver damage. In this case, I expect there to be no significant difference between the means of alanine aminotransferase and aspartate aminotransferase values. If there is no significant difference, this would indicate that either of these variables could be used as a proxy for liver damage in future analysis.\n\n## Describing the Data\n\n### Variables\n\nThe variable `lbxsatsi` is the alanine aminotransferase (ALT; in U/L) level measured in the blood serum of the NHANES participants. The ALT level was recorded in units/liter. This enzyme is specific to the liver and and elevated serum ALT is an indicator of liver damage.\n\nThe variable `lbxsassi` is the aspartate aminotransferase (AST; in U/L) level measured in the blood serum of the NHANES participants. The AST was also recorded in units/liter. This enzyme is present in the liver, heart, brain, kidneys, and muscles, but is classically used as a less-specific marker of liver damage.\n\n### Numerical Summaries/Visualizations\n\n#### Visualization\n\nFirst, the data was visualized to observe whether there appeared to be an association between ALT and AST. The dataset was filtered to the complete cases that had recorded ALT and AST values for this analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliver_damage_analA <- liver_damage %>%\n  filter(complete.cases(lbxsatsi, lbxsassi))\n\nliver_damage_analA %>%\n  ggplot(., aes(x = lbxsatsi, y = lbxsassi)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", col = \"red\",\n              se = TRUE, formula = y ~ x) +\n  theme(aspect.ratio = 1) +\n  labs(caption = \"Each subject had an ALT (in U/L) and AST (in U/L)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\nSince ALT and AST are paired by participant, we can calculate an additional variable, the difference between ALT and AST values to make a visual comparison of the difference between the two values more apparent. The difference in ALT and AST was calculated as ALT minus AST.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliver_damage_analA <- liver_damage_analA %>%\n  mutate(diff_ALT_AST = lbxsatsi - lbxsassi)\n```\n:::\n\n\n\nAfter calculating the difference in ALT and AST, I constructed a boxplot to visualize the distribution of the difference.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = liver_damage_analA, aes(x = diff_ALT_AST, y = \"\")) +\n  geom_violin(fill = \"dodgerblue\") +\n  geom_boxplot(width = 0.3, outlier.size = 3) +\n  stat_summary(fun = \"mean\", geom = \"point\",\n               shape = 23, size = 4, fill = \"blue\") +\n  labs(x = \"ALT - AST (difference in alanine and aspartate aminotransferase levels)\",\n       y = \"\", title = \"Distribution of Liver Enzyme Differences\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n### Numerical Summaries\n\nWhile it appears that most of the differences in ALT and AST values lie close to zero, numerical summaries for each variable and the difference of ALT minus AST were calculated before the main analysis was completed.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumm_anala <- as_tibble(bind_rows(\n  mosaic::favstats(~ lbxsatsi, data = liver_damage_analA),\n  mosaic::favstats(~ lbxsassi, data = liver_damage_analA),\n  mosaic::favstats(~ diff_ALT_AST, data = liver_damage_analA))) %>%\n  mutate(item = c(\"lbxsatsi\", \"lbxsassi\", \"diff_ALT_AST\")) %>%\n  select(item, n, mean, sd, min, median, max)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n```\n\n\n:::\n\n```{.r .cell-code}\nsumm_anala %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|item         |    n|      mean|       sd|  min| median| max|\n|:------------|----:|---------:|--------:|----:|------:|---:|\n|lbxsatsi     | 7216| 22.578575| 18.94270|    2|     18| 682|\n|lbxsassi     | 7216| 21.949279| 14.72411|    6|     19| 489|\n|diff_ALT_AST | 7216|  0.629296| 10.98709| -148|     -1| 193|\n\n\n:::\n:::\n\n\n\n## Main Analysis\n\nContinue here 12/08/2024... Test to see if worked\n\n## Conclusions\n\n# Analysis B: Comparing 2 Means with Independent Samples\n\n## The Question\n\n## Describing the Data\n\n## Main Analysis\n\n## Conclusions\n\n# Analysis C: Comparing 5 Means with Independent Samples\n\n## The Question\n\n## Describing the Data\n\n## Main Analysis\n\n## Conclusions\n\n# Analysis E: Analyzing a 2 x 5 Table\n\n## The Question\n\n## Describing the Data\n\n## Main Analysis\n\n## Conclusions\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}